name: use of secrets and env
on:
    push
env:
    image: nginx
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: docker login
          run: echo "docker login -u ${{ vars.username }} -p ${{ secrets.password }}"
        - name: docker build
          run: echo "docker push -t ${{ env.image }}"
    docker-build:
        runs-on: ubuntu-latest
        steps:
        - name: docker push
          run: echo "docker push -t ${{ env.image }}"