name: First Action workflow
on: push

jobs:
    First-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout the repo
          uses: actions/checkout@v6
        - name: welcome message
          run: echo "hello to the first githbub workflow"
        - name: list files
          run: ls
        - name: read the contents of the file
          run: cat readme.md