name: First Action workflow
on: push

jobs:
    First-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout the repo
          uses: actions/checkout@v6
        - name: setup 
          run: |
            echo "hello to the first githbub workflow"
            ls
            cat readme.md