name: Generate Ascii Demo

on:
    push
jobs:
    another-job:
        runs-on: ubuntu-latest
        steps:
             - name: checkout the repo
               uses: actions/checkout@v6
             - name: execute shell file
               run: |
                chmod +x ./ascii-generate.sh
                ./ascii-generate.sh
               
            
